import "~/styles/globals.css";

import { TRPCReactProvider } from "~/trpc/react";
import { BottomMenu, Footer, Header, ThemeProvider } from "../_components";

export const metadata = {
  title: "TS Todo App",
  description: "TS Todo App Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <TRPCReactProvider>
            <main className="flex min-h-[calc(100svh-7rem-1.5625rem)] items-center justify-center md:min-h-[calc(100svh-4rem-1.5625rem)]">
              {children}
            </main>
          </TRPCReactProvider>
          <BottomMenu />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
